# Generated by Django 5.0.4 on 2024-04-20 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstPage', '0006_contactbuyer_sent_at_contactseller_sent_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactbuyer',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactseller',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requested_product',
            name='requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
