# Generated by Django 5.0.2 on 2024-04-20 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstPage', '0007_alter_contactbuyer_sent_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactbuyer',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactseller',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
