# Generated by Django 5.0.2 on 2024-04-21 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstPage', '0012_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prd_category', to='firstPage.categories'),
        ),
        migrations.AddField(
            model_name='requested_product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='req_prd_category', to='firstPage.categories'),
        ),
    ]
