# Generated by Django 5.0.2 on 2024-04-21 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstPage', '0013_product_category_requested_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyers',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='firstPage.product'),
        ),
    ]
